### PR TITLE
Refactor codes and packaging before adding one last feature

### PR DESCRIPTION
**Pull request by jiah29**
## Context

Refactoring all the codes and restructure packages

## Your Changes

**Description**:
- Complete all test cases and achieve 100% test coverage
- Make sure that all test cases pass
- Refactor some classes to avoid long parameter list
- Move everything out of the spring-boot package
- Rename packages

**Type of change** (select all that apply):

- [x] Refactoring (changing code structure only)
- [x] Documentation update (adding more comments)
- [x] Test update (adding test code)

## Testing

Run all test cases, and everything passes!

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [x] One or two people have reviewed this pull request

### CODE REVIEW

**Comment by jiah29** [comment]
@elizabethhli @Danx1129 I have renamed the packages, let me know what you think 
https://github.com/autotrader-plus/autotrader-plus/pull/73/commits/6f5e327ed2968a3b8f63a8e62cced4b54dc6d788

**Comment by jiah29** [comment]
Alright just did the changes, and for the rest, we will leave it to another pr

**Review by elizabethhli — APPROVED** [review]
Looks good!

**Review by Danx1129 — APPROVED** [review]

**Review by Danx1129 — APPROVED** [review]
looks good

**Pull request merged**
