### PR TITLE
Created Unit Testing using Mocked Database through Mockito

### PR DESCRIPTION
**Pull request by jiah29**
## Linked Issue

#63

## Context

Previously, we only have integration testing that for all the methods that connects to the database. A mocked database is required to achieve unit testing.

## Your Changes

**Description**:
Uses Mockito to mock databased for classes in the informmationmanipulation packages: AuthenticateUserTest, ReturnCarInformationTest, ReturnMultipleCarsTest, and ReturnUserInformationTest.

**Type of change** (select all that apply):

- [x] New feature (additional functionality separate from existing code)
- [x] Test update (adding test code)

## Testing

Rerun all test cases; achieved 100% methods coverage!

## Notes

Missing mocked unit testing for AddUserTest.java (need to do that after the class is updated!)

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [x] One or two people have reviewed this pull request

### CODE REVIEW

**Review by elizabethhli — COMMENTED** [review]
Suggest using @BeforeTest to create the ConnectAutoTraderDB objects that are used for the tests in ConnectAutoTraderDBTest. Aside from that everything looks good!

**Comment by jiah29** [comment]
> Suggest using @BeforeTest to create the ConnectAutoTraderDB objects that are used for the tests in ConnectAutoTraderDBTest. Aside from that everything looks good!

Done!

**Review by Danx1129 — APPROVED** [review]
Approved

**Review by elizabethhli — APPROVED** [review]
Looks good!

**Pull request closed without merging**
