### PR TITLE
Adding Environment Variables

### PR DESCRIPTION
**Pull request by parthaba**
## Linked Issue
https://github.com/autotrader-plus/autotrader-plus/issues/44

## Your Changes
* Changed the database URL, database username, database password, Senso URL, and Senso key to the corresponding environment variable (which is configured on all our local machines)
* Made a documentation change on HttpResponseMain.java because a word was spelled wrong.

**Type of change** (select all that apply):

- [x] New feature (additional functionality separate from existing code)
- [x] Refactoring (changing code structure only)

## Testing

Ensured all existing tests run and tested everyone's local machines to ensure they all had the environment variables configured.

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [ ] One or two people have reviewed this pull request

### CODE REVIEW

**Comment by jiah29** [comment]
Yayy one less security concern!!! Looks good

**Review by jiah29 — APPROVED** [review]

**Comment by jiah29** [comment]
actually there are conflicts

**Comment by parthaba** [comment]
> actually there are conflicts

Conflicts that I don’t know how to resolve B)
It says I can’t resolve these conflicts in GitHub but I also don’t know how to use IntelliJ to do so

**Comment by jiah29** [comment]
I have to manually merge it and bypass the review part for some reasons....

**Pull request merged**
